### ISSUE TITLE
[REQ] Support for choosing which weapon deals damage

### ISSUE THREAD

**Issue by crashzk** [Whaliin/MagicBulletFix#2]
Would it be possible to have an option so that we can configure which weapon will count as damage or even grenades?

Example, I want to remove all damage from weapons, but leave all grenades.

**Comment by Whaliin** [comment]
Grenades will never be able to be fired from the magic bullet position so this request is not really feasible. All normal firing weapons are already detected and handled by the plugin.

The only way I can think of grenade damage ever being ignored is if their grenade deals damage the exact same tick that they fired a magic bullet. The chance of this happening is honestly so unlikely that I do not think it will ever even be a problem.
